// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TandemBackend.Data;

#nullable disable

namespace TandemBackend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260423185713_addPracticeTasks")]
    partial class addPracticeTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TandemBackend.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PracticeTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTopicId")
                        .IsUnique();

                    b.ToTable("CodeCompletion");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletionQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeCompletionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeCompletionId");

                    b.ToTable("CodeCompletionQuestion");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletionQuestionRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeCompletionRuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeCompletionRuId");

                    b.ToTable("CodeCompletionQuestionRu");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletionRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeCompletionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeCompletionId")
                        .IsUnique();

                    b.ToTable("CodeCompletionRu");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PracticeTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTopicId")
                        .IsUnique();

                    b.ToTable("CodeEditor");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditorQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeEditorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExpectedAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StarterCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeEditorId");

                    b.ToTable("CodeEditorQuestion");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditorQuestionRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeEditorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeEditorRuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExpectedAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StarterCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeEditorRuId");

                    b.ToTable("CodeEditorQuestionRu");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditorRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeEditorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeEditorId")
                        .IsUnique();

                    b.ToTable("CodeEditorRu");
                });

            modelBuilder.Entity("TandemBackend.Models.EnTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EnTopics");
                });

            modelBuilder.Entity("TandemBackend.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("TandemBackend.Models.LessonRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("LessonsRu");
                });

            modelBuilder.Entity("TandemBackend.Models.PracticeTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("PracticeTopic");
                });

            modelBuilder.Entity("TandemBackend.Models.PracticeTopicRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PracticeTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTopicId")
                        .IsUnique();

                    b.ToTable("PracticeTopicRu");
                });

            modelBuilder.Entity("TandemBackend.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PracticeTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PracticeTopicId")
                        .IsUnique();

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("TandemBackend.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestion");
                });

            modelBuilder.Entity("TandemBackend.Models.QuizQuestionRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizRuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizRuId");

                    b.ToTable("QuizQuestionRu");
                });

            modelBuilder.Entity("TandemBackend.Models.QuizRu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId")
                        .IsUnique();

                    b.ToTable("QuizRu");
                });

            modelBuilder.Entity("TandemBackend.Models.RuTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RuTopics");
                });

            modelBuilder.Entity("TandemBackend.Models.TaskStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EarnedPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaskStats");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletion", b =>
                {
                    b.HasOne("TandemBackend.Models.PracticeTopic", "PracticeTopic")
                        .WithOne("CodeCompletion")
                        .HasForeignKey("TandemBackend.Models.CodeCompletion", "PracticeTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeTopic");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletionQuestion", b =>
                {
                    b.HasOne("TandemBackend.Models.CodeCompletion", "CodeCompletion")
                        .WithMany("Questions")
                        .HasForeignKey("CodeCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeCompletion");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletionQuestionRu", b =>
                {
                    b.HasOne("TandemBackend.Models.CodeCompletionRu", "CodeCompletionRu")
                        .WithMany("Questions")
                        .HasForeignKey("CodeCompletionRuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeCompletionRu");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletionRu", b =>
                {
                    b.HasOne("TandemBackend.Models.CodeCompletion", "CodeCompletion")
                        .WithOne("CodeCompletionRu")
                        .HasForeignKey("TandemBackend.Models.CodeCompletionRu", "CodeCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeCompletion");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditor", b =>
                {
                    b.HasOne("TandemBackend.Models.PracticeTopic", "PracticeTopic")
                        .WithOne("CodeEditor")
                        .HasForeignKey("TandemBackend.Models.CodeEditor", "PracticeTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeTopic");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditorQuestion", b =>
                {
                    b.HasOne("TandemBackend.Models.CodeEditor", "CodeEditor")
                        .WithMany("Questions")
                        .HasForeignKey("CodeEditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeEditor");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditorQuestionRu", b =>
                {
                    b.HasOne("TandemBackend.Models.CodeEditorRu", "CodeEditorRu")
                        .WithMany("Questions")
                        .HasForeignKey("CodeEditorRuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeEditorRu");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditorRu", b =>
                {
                    b.HasOne("TandemBackend.Models.CodeEditor", "CodeEditor")
                        .WithOne("CodeEditorRu")
                        .HasForeignKey("TandemBackend.Models.CodeEditorRu", "CodeEditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeEditor");
                });

            modelBuilder.Entity("TandemBackend.Models.LessonRu", b =>
                {
                    b.HasOne("TandemBackend.Models.Lesson", "Lesson")
                        .WithOne("LessonRu")
                        .HasForeignKey("TandemBackend.Models.LessonRu", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TandemBackend.Models.PracticeTopic", b =>
                {
                    b.HasOne("TandemBackend.Models.Lesson", "Lesson")
                        .WithOne("PracticeTopic")
                        .HasForeignKey("TandemBackend.Models.PracticeTopic", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TandemBackend.Models.PracticeTopicRu", b =>
                {
                    b.HasOne("TandemBackend.Models.PracticeTopic", "PracticeTopic")
                        .WithOne("PracticeTopicRu")
                        .HasForeignKey("TandemBackend.Models.PracticeTopicRu", "PracticeTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeTopic");
                });

            modelBuilder.Entity("TandemBackend.Models.Quiz", b =>
                {
                    b.HasOne("TandemBackend.Models.PracticeTopic", "PracticeTopic")
                        .WithOne("Quiz")
                        .HasForeignKey("TandemBackend.Models.Quiz", "PracticeTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeTopic");
                });

            modelBuilder.Entity("TandemBackend.Models.QuizQuestion", b =>
                {
                    b.HasOne("TandemBackend.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TandemBackend.Models.QuizQuestionRu", b =>
                {
                    b.HasOne("TandemBackend.Models.QuizRu", "QuizRu")
                        .WithMany("Questions")
                        .HasForeignKey("QuizRuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizRu");
                });

            modelBuilder.Entity("TandemBackend.Models.QuizRu", b =>
                {
                    b.HasOne("TandemBackend.Models.Quiz", "Quiz")
                        .WithOne("QuizRu")
                        .HasForeignKey("TandemBackend.Models.QuizRu", "QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletion", b =>
                {
                    b.Navigation("CodeCompletionRu");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeCompletionRu", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditor", b =>
                {
                    b.Navigation("CodeEditorRu");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TandemBackend.Models.CodeEditorRu", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("TandemBackend.Models.Lesson", b =>
                {
                    b.Navigation("LessonRu");

                    b.Navigation("PracticeTopic");
                });

            modelBuilder.Entity("TandemBackend.Models.PracticeTopic", b =>
                {
                    b.Navigation("CodeCompletion");

                    b.Navigation("CodeEditor");

                    b.Navigation("PracticeTopicRu");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TandemBackend.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizRu");
                });

            modelBuilder.Entity("TandemBackend.Models.QuizRu", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
